### Q1

In [1]:
# Q1
import numpy as np

a = np.array([4, 8, 12, 16, 20])
print("Original array:", a)

# a) add 2
print("After adding 2:", a + 2)

# b) multiply by 3
print("After multiplying by 3:", a * 3)

# c) divide by 2
print("After dividing by 2:", a / 2)

Original array: [ 4  8 12 16 20]
After adding 2: [ 6 10 14 18 22]
After multiplying by 3: [12 24 36 48 60]
After dividing by 2: [ 2.  4.  6.  8. 10.]


### Q2

In [2]:
# Q2 a)
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original:", arr)
print("Reversed:", arr[::-1])

Original: [1 2 3 6 4 5]
Reversed: [5 4 6 3 2 1]


In [3]:
# Q2 b) i.
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
max_count = counts.max()

for v, c in zip(values, counts):
    if c == max_count:
        print("Most frequent value:", v)
        print("Count:", c)
        print("Indices:", np.where(x == v)[0])

Most frequent value: 1
Count: 5
Indices: [0 5 7 8 9]


In [4]:
# Q2 b) ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
max_count = counts.max()

for v, c in zip(values, counts):
    if c == max_count:
        print("Most frequent value:", v)
        print("Count:", c)
        print("Indices:", np.where(y == v)[0])

Most frequent value: 1
Count: 3
Indices: [0 1 2]
Most frequent value: 3
Count: 3
Indices: [4 8 9]


### Q3

In [5]:
# Q3
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)

# a) 1st row, 2nd column
print("1st row, 2nd column:", arr[0, 1])

# b) 3rd row, 1st column
print("3rd row, 1st column:", arr[2, 0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


### Q4

In [6]:
# Q4
Himantveer_Kaur = np.linspace(10, 100, 25)
print(Himantveer_Kaur)

print("Dimensions:", Himantveer_Kaur.ndim)
print("Shape:", Himantveer_Kaur.shape)
print("Total elements:", Himantveer_Kaur.size)
print("Data type:", Himantveer_Kaur.dtype)
print("Total bytes:", Himantveer_Kaur.nbytes)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200


In [7]:
# Q4 transpose using reshape
col = Himantveer_Kaur.reshape(25, 1)
print("Shape after reshape:", col.shape)
print(col)

Shape after reshape: (25, 1)
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [8]:
# Q4 using T attribute
print("Shape using T:", Himantveer_Kaur.T.shape)
print("Same as original?", np.array_equal(Himantveer_Kaur.T, Himantveer_Kaur))

Shape using T: (25,)
Same as original? True


No, we cannot get the same result with `T` here. A 1-D array has only one axis, so `T` returns the same array with shape `(25,)`. Reshape is needed to make it a 2-D array of shape `(25, 1)` (or `(1, 25)`); after that `T` would work.

### Q5

In [9]:
# Q5
ucs420_himantveer_kaur = np.array([[10, 20, 30, 40],
                                   [50, 60, 70, 80],
                                   [90, 15, 20, 35]])
print(ucs420_himantveer_kaur)
print("Shape:", ucs420_himantveer_kaur.shape)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Shape: (3, 4)


In [10]:
# Q5 mean, median, max, min, unique
print("Mean:", np.mean(ucs420_himantveer_kaur))
print("Median:", np.median(ucs420_himantveer_kaur))
print("Max:", np.max(ucs420_himantveer_kaur))
print("Min:", np.min(ucs420_himantveer_kaur))
print("Unique elements:", np.unique(ucs420_himantveer_kaur))

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [11]:
# Q5 reshape to 4 rows, 3 columns
reshaped_ucs420_himantveer_kaur = ucs420_himantveer_kaur.reshape(4, 3)
print(reshaped_ucs420_himantveer_kaur)
print("Shape:", reshaped_ucs420_himantveer_kaur.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Shape: (4, 3)


In [12]:
# Q5 resize to 2 rows, 3 columns
resized_ucs420_himantveer_kaur = np.resize(ucs420_himantveer_kaur, (2, 3))
print(resized_ucs420_himantveer_kaur)
print("Shape:", resized_ucs420_himantveer_kaur.shape)

[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
